version: "3.8"

services:
  redmine:
    image: redmine:latest
    container_name: redmine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
    depends_on:
      - db
    volumes:
      - redmine_files:/usr/src/redmine/files
      - ./themes:/usr/src/redmine/themes
      - ./public/images:/usr/src/redmine/public/images
      - ./public/stylesheets:/usr/src/redmine/public/stylesheets
      - ./public/javascripts:/usr/src/redmine/public/javascripts
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./docker-entrypoint-wrapper.sh:/docker-entrypoint-wrapper.sh
      - ./init-redmine-logo.sh:/usr/local/bin/init-redmine-logo.sh
    entrypoint: ["/docker-entrypoint-wrapper.sh"]
    command: ["rails", "server", "-b", "0.0.0.0"]

  db:
    image: mysql:5.7
    container_name: redmine_db
    ports:
      - "3306:3306"   # ‚Üê ESTO ES LO QUE FALTABA
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - redmine_db:/var/lib/mysql

volumes:
  redmine_files:
  redmine_db:
